### ISSUE TITLE
Naked Yoga event?

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#10]
Debate:

**Comment by findkiko** [comment]
Saturday mornings are less busy than usual.
Can we be compensated for a percantage of revenue?
Regular membership can cover 1 morning per week, suggest 1.5 memberships for 2 mornings per week.

**Comment by ghost** [comment]
We have decided that naked yogo can happen Sat and Sun mornings between 6-10am for a regular membership and a fixed percentage of all donations.
