### ISSUE TITLE
Bring leftover back room junk to thrift store 

### ISSUE THREAD

**Issue by chiselinc** [DecentralVan/decentral#122]
@rhodes since that lady stole your cat carrier, do you want the one from the back room? Pretty sure it used to be for Eleanor

**Comment by chiselinc** [comment]
I'm a dick for not doing this among a few other things (although i swear i do a ton you guyyyyyssss!) so I'll try to find a time to do so - maybe when Jenni gets back next week she and I can team up

**Comment by astupidmoose** [comment]
I'm gonna make myself available soon with my pickup (next week or so) so as long as weather is permitting we can throw some stuff into he back and go to drop stuff off

**Comment by moonunderwater** [comment]
I can help, when there is no snow :) my car doesn't like snow.

**Comment by chiselinc** [comment]
Mike Olthoff is going to help me on Tuesday morning, thanks though! 💟
