### ISSUE TITLE
Track expenses better

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#126]
We need to track and categorise expenses better, so we know what we're spending on door-locks, renovations, cleaning, equipment etc.

**Comment by findkiko** [comment]
Found this today: https://www.buxfer.com/
It has a free tier and pretty simple API etc.

**Comment by chiselinc** [comment]
I just gotta say I think this is really going well, and I like the systems yall have put into place. Once the bounty system gets solidified this is gonna be great.
