### ISSUE TITLE
Track and store production secrets better

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#127]
We're all over the place right now; there's passwords on scraps of paper, some others in a google spreadsheet of Cams, some stored by me.

We could use a more formal system for logins etc.

**Comment by chiselinc** [comment]
We can discuss this Thurs night at the potluck/Wikithon and come up with a proposed solution

**Comment by cammyjee** [comment]
I setup a shared folder for lastpass for our secrets. If people want to join I can share it with you, otherwise you can just send them to me, and I'll put them in there. I know it might not be the ideal solution but I'm just doing it for now
