### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#13]
Create some guidelines and ground rules.
Add them to the wiki.

**Comment by findkiko** [comment]
Just leaving a collection of useful links/inspiration here:
https://wiki.xinchejian.com/wiki/London_Hackerspace_Rules
https://wiki.xinchejian.com/wiki/Nottingham_Hackerspace_Rules
https://wiki.xinchejian.com/wiki/Sydney_Hackerspace_Rules
https://wiki.xinchejian.com/wiki/Membership_Code_of_Conduct

**Comment by chiselinc** [comment]
Wow just saw this. This falls within my wheelhouse. I can have a loose structure drafted up before our next meeting, reach out for group consensus on Slack, and we can collaborate to finalize? I'm throwin that bizness up on my Trello list now.
