### ISSUE TITLE
Switch bills to bylls

### ISSUE THREAD

**Issue by cammyjee** [DecentralVan/decentral#138]
Tangerine account is almost empty, bylls.com pays your bills with bitcoin.

https://bylls.com/

**Comment by findkiko** [comment]
Bylls is on hiatus or defunct at the moment.
There's enough money for Jan (20th) internet in the account. We need a workaround by 20th Feb.

**Comment by astupidmoose** [comment]
I got an email from bylls about this a few weeks ago:

> You will still be able to pay your bills manually by contacting us directly. In order to pay a bill manually, please follow these steps:
> 1.	Contact us at info@bylls.com
> 2.	State which bill you want to pay
> 3.	State your bill number
> 4.	State the amount
> 5.	If you have not already registered this biller, or if you are unsure if the biller is registered, let us know and we will manually check our list and tell you.
> 6.	We will manually send you a Bitcoin address and a price quote to pay the bill.
> 

Should still work that way if needed.

**Comment by findkiko** [comment]
Bump. To my knowledge we've got 10 days left to pay the internet bill.

**Comment by chiselinc** [comment]
Has anything happened on the Internet bill? If not, i can pay it this month interim, i actually came across the post it where i have the account info, from last time it crashed. 

Let me know if bylls is coming through otherwise I'll pay it before the deadline passes

**Comment by cammyjee** [comment]
@chiselinc yup the auto payment failed last night funny enough. @astupidmoose I can't remember our stipulation for membership. Would you want to pay our bill at least until bylls is automated again?
