### ISSUE TITLE
Consolidate Github Organizations

### ISSUE THREAD

**Issue by cammyjee** [DecentralVan/decentral#139]

**Comment by chiselinc** [comment]
@rhodes let's get on top of this before the next meeting?

**Comment by ghost** [comment]
I'll kill d-ctrl (move the code back to this org). Then we can rename this org to dctrl1337 or somesuch

**Comment by ghost** [comment]
d-ctrl is no more

**Comment by cammyjee** [comment]
Dctrlvan would be more consistent with branding of Twitter and such accounts where we couldn't get DCTRL
