### ISSUE TITLE
create slackbot to post info@decentral emails into a slack channel

### ISSUE THREAD

**Issue by chiselinc** [DecentralVan/decentral#143]

**Comment by findkiko** [comment]
https://github.com/SRARAD/slack-email

**Comment by BenMorganIO** [comment]
I'm literally trying to do this right now the opposite way with Sending bitcoin from slack and notifications via email and receive emails with bitcoin addresses. You can create a simple Rails app using [Griddler](https://github.com/thoughtbot/griddler) and just use the Slack API to post to the chat.

**Comment by chiselinc** [comment]
This doesn't really fit with the system we're rocking these days, I'm closing
