### ISSUE TITLE
Wishlist 2.0

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#148]
(Edit as necessary)

## Medium ticket items ($40 - $250)

- Vocal recording panel [$59 USD ](https://www.amazon.com/Marantz-Professional-Sound-Shield-Compact/dp/B01GDB7296/ref=sr_1_2?s=musical-instruments&ie=UTF8&qid=1481607410&sr=1-2&keywords=vocal+recording+panel)
- Hammock(s) [$34 CAD](https://www.amazon.ca/OFKP-Camping-Hammock-Colorful-Polyester/dp/B018209VKE/ref=sr_1_22?ie=UTF8&qid=1481611182&sr=8-22&keywords=hammock)
- Rubber floor mat (heavy duty) - For standing work in back room. [$40 CAD](https://www.amazon.ca/AnthroDesk-standing-anti-fatigue-floor-Black/dp/B00UWFEGT4/ref=sr_1_1?ie=UTF8&qid=1481612012&sr=8-1&keywords=standing+mat)
- Tournament chess board [$22 CAD](https://www.amazon.ca/Best-Value-Tournament-Chess-Set/dp/B003DMITE6/ref=sr_1_1?ie=UTF8&qid=1481612085&sr=8-1&keywords=tournament+chess+board)
- Table lamps (atmospheric) [$26 CAD](https://www.amazon.ca/Etekcity-Living-Color-Desk-Table/dp/B017SDF8XA/ref=sr_1_4?ie=UTF8&qid=1481612429&sr=8-4&keywords=table+lamp)
- Webcam (back room broadcasting) [$90 CAD](https://www.amazon.ca/Logitech-Webcam-Pro-C920-Packaging/dp/B006JH8T3S/ref=sr_1_1)
- Paint (main room decorating)
- Lumber for main room sofa plinth construction
- A couple of nice lights for filming/streaming meetups
- A couple color filter sheets? [$24.71 CAD](https://www.amazon.ca/Neewer-30x30CM-Transparent-Correction-Flashlight/dp/B01CCIKB5Q/ref=sr_1_1?ie=UTF8&qid=1481613585&sr=8-1&keywords=color+filter+sheets)
- Another large rug [Kiko requested at March 6 2017 meeting, $100ish agreed upon budget]
- Scissor mic stands
- Another acoustic guitar
- Mini Hockey / Mini Golf
- Thai Cushions
## Sundries (<$40)

- Foot rest covers (plastic/shoe proof)
- Interesting money for the money wall (numismatics)
- More board games etc
- Package of lighters
- Light Bulbs
- Shot glasses
- Lacrosse Massage Balls
- New tripod

**Comment by JayeHarrill** [comment]
TV mount is missing under $40 - $250

Below are just thoughts / suggestions take em or leave em as you will.
____
Shelving for video games / systems? (can also be sourced or built)

If under-stairs room is positioned to a "quiet room". Then would a yoga mat or thai mat and a meditation stump / stool / pillow make sense?

Tournament chess can also be accomplished using an app timer if need be. 

Crib board?

Is there any room for an advertising budget with Google AdWords / Facebook? (I don't think it would be placed under wishlist)

**Comment by findkiko** [comment]
Depending on the VESA standard used I already have a tv mount at the space.
We also already have 3-4 yoga mats around (hallway cupboards)
Re: under the stairs, I think we should remodel then see what would work well once the space is clear and better lit etc.

**Comment by nicdex** [comment]
I have an HD projector sitting in a box at home. I haven't unboxed it in 4 years. I could bring it and check how good it still works, far as I know lamp is recent (few hours on it). I could evaluate how much I would charge for it.

**Comment by findkiko** [comment]
Thanks! Yeah bring it down and we'll check it out if its not too much hassle.

**Comment by nicdex** [comment]
I'll bring it next Monday or Tuesday, depending if I work from home.

**Comment by nicdex** [comment]
Projector is still working great, of course I'll let you guys test it. I was thinking 150$ or two month of rent for it.

**Comment by BenMorganIO** [comment]
> Artwork budget

@daniel-johnson maybe you could help with this? ;)

**Comment by chiselinc** [comment]
@findkiko since this has been trucking along pretty well, I'm going to incorporate the old wiki "wishlist" page here and delete it-- that way it doesn't clog up the more structured static-info pages

Also, do we still need a 12-volt for the maglock system?

**Comment by chiselinc** [comment]
I have ported all this info into a kanban board under "Projects" called Wishlist to Shopping List
