### ISSUE TITLE
Fix Rust on Pi

### ISSUE THREAD

**Issue by paullucas** [DecentralVan/decentral#149]
Segmentation Fault whenever running rustup, rustc, or cargo. 
See this issue for more information: [https://github.com/rust-lang-nursery/rustup.rs/issues/439](https://github.com/rust-lang-nursery/rustup.rs/issues/439)

Attempted the following patchelf solution:
`$ curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- --channel=nightly`
`$ sudo patchelf --add-needed /usr/lib/libpthread.so.0 $(which rustc)`
`$ sudo patchelf --add-needed /lib/ld-linux-armhf.so.3 $(which cargo)`

No luck. Uninstalled rustup, rustc, and cargo for now.

**Comment by findkiko** [comment]
Not totally sure why you need/want rust on the receiving end? If you insist, you could consider cross compiling if you want to run an animation while not present. http://stackoverflow.com/a/30833842
