### ISSUE TITLE
Stop using google docs.

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#15]
Debate alternatives to using google docs for data storage.
Synchronising information is a pain with other systems but I do understand it's relatively user-friendly, It doesn't check whether user input is accurate, which was awkward when exporting eg. apparently empty cells that just have a space in them.

**Comment by chiselinc** [comment]
Are we still feeling this? My understanding is we pretty much only use Google Docs for the accounting spreadsheet, and we could indeed look for other options... maybe Taiga.io has an excel-like module?

**Comment by chiselinc** [comment]
@findkiko We are most of the way there on this, right? Except for spreadsheets IIRC. Accounting and membership records are already on the table for sprucing up, so it would be the perfect time to get a consensus and move the system to something else.
