### ISSUE TITLE
Write down total kegerator expenses

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#150]

**Comment by chiselinc** [comment]
@TannaPo can we do this soon - running expenses list? Dctrl will recomp me for the new kegs

**Comment by TannaPo** [comment]
I'd like to sit down and make a spreadsheet for this.  How do I access the receipts and accounting records?

**Comment by cammyjee** [comment]
@TannaPo Just shared with you a spreadsheet I made which includes most of the kegerator
