### ISSUE TITLE
Create DCTRL Stickers

### ISSUE THREAD

**Issue by cammyjee** [DecentralVan/decentral#151]
I'll look into this

**Comment by findkiko** [comment]
http://hexb.in/

**Comment by cammyjee** [comment]
@findkiko Do you think we should do hexagon? I was thinking square because of the "squareness" of the logo. Also, do you think the PNG file you made good enough quality. I just uploaded one to decentral/assets

**Comment by findkiko** [comment]
Agree it's not a natural fit. I'm just a neat freak and all the hexagons go so nice together! Whatever you think really.

**Comment by BenMorganIO** [comment]
I'd recommend [Sticker Mule](https://www.stickermule.com/ca)
