### ISSUE TITLE
Create bounty for Bill acceptor integrations

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#159]

**Comment by BenMorganIO** [comment]
Bounty? Would love to know more.

**Comment by findkiko** [comment]
https://github.com/DecentralVan/decentral/projects/3

We agreed there's 100 bucks in it for whoever gets the bill acceptor we have lying around to talk to a database of our members. So far some nibbles but nobody's taken the time to get it working.

https://github.com/DecentralVan/decentral/blob/master/assets/Billacceptor_Apex_Manual.pdf
