### ISSUE TITLE
Get a VPN for the space

### ISSUE THREAD

**Issue by cammyjee** [DecentralVan/decentral#163]
Multiple users as a member perk?

**Comment by JayeHarrill** [comment]
I've used Nord VPN before. But I didn't use the VPN very much.. I know I'm bad.. Not sure if anyone else has tried them.

**Comment by astupidmoose** [comment]
I've used privateinternetaccess for a long time and never had major issues, with the exception of the IP I'm on being banned from certain sites but an IP cycle fixes that usually. I dunno the issues revolving around multiple people using a VPN. Can the router be configured to tunnel through a VPN so it's seemless?

**Comment by JayeHarrill** [comment]
Do we have a router with Open WRT?

**Comment by cammyjee** [comment]
I think the router Jacob left has OpenWRT on it. Not sure if we're still using it. @astupidmoose PIA has worked very well for me too.

**Comment by astupidmoose** [comment]
PIA has a limit of 5 devices per account, NordVPN has a limit of 6. 

However if we configure the router to be the device all traffic is filtered through, then that's only 1 device. We wouldn't be able to have everyone be using it on their phones etc too, but again anything connected to wifi should automatically benefit. 

I'm not sure what services are currently being broadcast outside the network, so i'm not sure how it would affect connecting to those remotely if at all but we would want to take that into consideration

**Comment by mitchplze** [comment]
If someone knows what router we're using internally, I can help setup a VPN on it
