### ISSUE TITLE
Re-affix RFID sticker on front door

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#164]
(So people know where to swipe their keyfobs)

**Comment by chiselinc** [comment]
Do we have a sticker, or do we need one?

**Comment by astupidmoose** [comment]
I have a "forever alone" sticker I could donate. 

Lol

**Comment by findkiko** [comment]
Was previously just a square of silver duct tape with rfid logo drawn on in sharpie. Don't put too much love into it as it frequently gets painted over when they un-graffiti the entrance.

**Comment by chiselinc** [comment]
Bitcoin baron.
