### ISSUE TITLE
Fix Vending Machine Pi

### ISSUE THREAD

**Issue by ghost** [DecentralVan/decentral#166]

**Comment by findkiko** [comment]
Just a thought, but it might not be getting a great wifi signal inside the vending machine, now that we've moved the router down the other end of the room. It's worth a check... Maybe reboot it with the door open?

I highly recommend `wavemon` as a way more fun replacement to using `iwconfig` to check wifi strength btw.

**Comment by findkiko** [comment]
DHCP is failing for some reason. Its now hooked up to the monitor in the back room for better debugging...
