### ISSUE TITLE
Determine what "successful meetup" means.

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#167]
We agreed successful meetups are our best avenue for recruitment. Finalise the rules that activate reward bounties/perks.

- X new faces?
- Full explanation of the space ethos & opportunity.
- Full description on meetup.com 72hrs prior to event.
- Matching dctrl google calendar entry.

Or...Approved by member quorum.

**Comment by moonunderwater** [comment]
What about including 'clean-up after event' on this list, to avoid future cleaning bounty related questions?

**Comment by JayeHarrill** [comment]
I am in favour of this.

**Comment by findkiko** [comment]
I guess this now just needs a wiki page with the final rules, then it can be closed out.

**Comment by moonunderwater** [comment]
I can create the wiki page one day soon (it will be a great excuse to learn how to make a wiki page :)

**Comment by moonunderwater** [comment]
What were the final decisions for: 
-amount of people
-other little details:

**Comment by cammyjee** [comment]
Ok I just wrote up a wiki page, feel free to edit, or comment. I put that 10 new/nonmembers have to be at the meetup but that number can change.

https://github.com/DecentralVan/decentral/wiki/What-Determines-a-%22Successful-Meetup%22

Sorry @moonunderwater I didn't see that you wanted to make it! I just wrote one up. But there will be plenty more wiki entries, I'm sure.

**Comment by JayeHarrill** [comment]
Looks great

**Comment by moonunderwater** [comment]
@cammyjee no worries :)
