### ISSUE TITLE
New rugs all over the place!

### ISSUE THREAD

**Issue by moonunderwater** [DecentralVan/decentral#168]
Chelsea and I took measurements around all the spaces with rugs and floor things. 

Top priority to change: _back room floor thing_ and _bottom of stairs mats_. I am thinking perhaps some rubber ones there. 

Then I would like to change the one near the beer machine and the one in the main room. Thoughts on those? 

I will be heading to buy them during this week. Canadian tire has a bunch on sale...

**Comment by findkiko** [comment]
For reference; this is what we got for the main room last time. http://www.ikea.com/ca/en/catalog/products/10328634/#/00322029
I think its been a great success for $70, though it does need a thorough clean after 10-months or so of hard duty.

**Comment by moonunderwater** [comment]
rugs purchased, for all places with rugs except for large main room one. 100$ was spent, plus 10$ for gas. I will leave them all 'unwrapped' until folks give consent that they like them :) 

I will drop them off some point in the near future!

**Comment by findkiko** [comment]
Thanks!
