### ISSUE TITLE
Fix nvm overiding node version for other apps on hashi box

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#171]
I just spent 20min diagnosing/fixing etherpad as node command had been hijacked. (It had been running from memory until a recent reboot.) I'm getting pretty tired of fixing things that node versioning breaks... (The other week it was the vending machine.)

I had to temporarily hard code the etherpad scripts to `/usr/bin/node` but this will break on an upgrade of etherpad.

This was caused by `/usr/local/bin` being before `/usr/bin` in `$PATH`. I think this should really be the other way around in this instance; ie. if an app needs something other than upstream node, then it should call it directly. Maybe the solution would be to call the manually installed node `newnode` or something so there's no namespace clash.

I'm not even sure what other applications on that system are calling `node` and not getting the expected system version.

@asoltys

**Comment by findkiko** [comment]
I think this should be moot now. nodejs v7.4.0 is upstream. There's new etherpad-lite packages too. I think we just need to upgrade everything and remove any manually installed stuff. I'll wait until later though as people are using etherpad to do tonights meeting agenda.

**Comment by asoltys** [comment]
doh, sorry for the hassle.  we could consider dockerizing all our services so they don't clash in the future.

**Comment by findkiko** [comment]
K.
I'm going to move these over [here](https://github.com/DecentralVan/sysadmin/issues/) as this was supposed to be the _meatspace_ issues/wiki. We just never had anywhere else for the software stuff until now.
