### ISSUE TITLE
Create crowd-funding campaign for VR headset

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#173]
Draft a campaign for raising the 50% headset funding, for distrubution to members and friends of the space.

Document the process, timeline, budget and management strategy.

**Comment by cammyjee** [comment]
Thanks for making this Kiko, I didn't realize you had made an issue.

So far we have 8 members who have committed to pledging $50. We need a total of 12 members pledging $50 for crowdfunding 50% of the HTC Vive. It's costs $1,149 CAD. So if we hit $600 crowdfunded in total, the commons will pay for the rest.

If you want to pay in BTC I've created a wallet. Just please let me know if you've sent in your $50 or not. Public address is 18JvzxMMuXtxHfcFxktaWpqWfnvxGmQoZj

https://store.us.vive.com/store?Action=DisplayPage&Env=BASE&Locale=en_CA&SiteID=htcus&id=ThreePgCheckoutShoppingCartPage

Once we have $600 we'll need someone to buy the HTC Vive outright ( @TRhode ?). We'll be able to pay them back, half from the crowdfund and half from the commons fund.

I'm hoping we can reach our goal by this weekend, and pick up the Vive sometime next week.

Members committing:
Cam
Manuel
Kiko
Taylor
Jared
Jen
Adam S.
Daniel

**Comment by JayeHarrill** [comment]
Cam - $75
Manuel - ?
Kiko - $50
Taylor - $75
Jared - $75
Jen - $50
Adam S. - $75
Daniel - $76? ($75, but he one upped us)
Kenta - $25 (March) + $25 (April)
Chelsea - $50
Nickolas - $100
Mike - $50

Not counting Manual we have $751/$800 committed, the extra is for paying for half of the price for a new CPU.

**Comment by astupidmoose** [comment]
I had also committed $50. -Mike
