### ISSUE TITLE
Document how to host a google hangouts session.

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#175]
Currently this is a combination of luck and witchcraft.

The media pc is typically in various states of mis-configuration. Some things that need to be documented so the start of a hangout isn't such a shit-show when Cam/Taylor are away. (Basically make a fool-proof checklist).

- Which ports the HDMI cable should be plugged into.
- The user/password to log-in to to the operating system if any.
- How to turn on/off the PA system/mixer.
- The specific plugs that should be connected to the sound mixer. Any switches/dials that need setting.
- How to configure the sound settings for the Yeti Mic, including muting/un-muting.
- The best browser to use for hangouts (there are several installed on the machine).
- Where to find the username/password for dctrl google account.
- Where to find the username/password to access slack on an untrusted machine for copy/pasting invite links.

**Comment by chiselinc** [comment]
I'm thinking it's best to wait on this till we get the new rig set up, as some of our strange problems might solve themselves with better equipment? I'm making a placeholder orientation page in the wiki just as an infrastructural reminder that this has to be inserted eventually (which is what she said)
