### ISSUE TITLE
Paint over canvases

### ISSUE THREAD

**Issue by chiselinc** [DecentralVan/decentral#177]
Canvases from abandoned paintings can be repurposed- they are on top of the hall cupboard, next to the stock pot

**Comment by manv3lez** [comment]
@findkiko I want to paint over the canvases. I can't find the paint brush we used to paint the door frame on the voice room. Do you know where I could find it please? Thanks : )

**Comment by TannaPo** [comment]
I propose an art party. We can hang the art up or people can take it home. I have a shit ton(metric) of paints and brushes at home as well.

**Comment by findkiko** [comment]
Behind the door in the back room is a box of decorating supplies. But hold off on this as I've got an idea and some some large additional canvases I'm going to bring to the space.
