### ISSUE TITLE
Front door

### ISSUE THREAD

**Issue by ghost** [DecentralVan/decentral#18]
We need a way to indicate the location of the fob. Maybe make the numbers on the door more readable.

**Comment by findkiko** [comment]
Stencil or LEDs?

**Comment by findkiko** [comment]
I moved the RFID reader over to the handle side of the door so have put a temporary marker on the outside (silver duct tape). A more permanent solution is still required.

**Comment by findkiko** [comment]
Working fine for now. Closing.
