### ISSUE TITLE
Available Resources for Projects

### ISSUE THREAD

**Issue by chiselinc** [DecentralVan/decentral#180]
David, Taylor and I are sorting more stuff out and we've found some cool project resources in the backroom-- could move forward some issues that we've let stagnate, and even set the foundation for new bounty projects.

Running list:

* Parts to build a back door maglock
* A third projector?! (Working? Someone needs to track down a power cord from the electronics drawer to try it out)
* Lava lamp which will work if you pick up a 30 watt type r12 bulb (120V/60Hz)

**Comment by findkiko** [comment]
Yup.
The grey projector is also mine(!) but is up for dctrl consumption, its only 800x600 resolution but still good for throwing up a big diagram or logo or something.
Installing the 2nd mag-lock has been an open issue for a while, there's debate if it will actually be useful on the back room, it will certainly be a Taylor head hazard though.
Lava lamp was rescued from Freddies stuff, think it just needs a bulb as you say.
