### ISSUE TITLE
Deploy Dctrl.ca Website Live

### ISSUE THREAD

**Issue by cammyjee** [DecentralVan/decentral#181]
We've simplified the website so that it can be deployed. @TRhode Could you put a simple explanation of the bounty system so visitors can understand it's still a work in progress but can understand what it's for? @asoltys could you point dctrl.ca after Taylor's push/commit?

**Comment by asoltys** [comment]
server appears to be down.. might need to be rebooted/turned on/plugged in?

**Comment by findkiko** [comment]
I updated the hashi server BIOS yesterday to come back up after a power outage etc. It should be a bit more reliable now.
I was also showing Taylor the systemd configs yesterday, but I'm not really sure how that node specific process manager you had set up works. We could probably use a run-through from you at some point @asoltys :smile:

**Comment by cammyjee** [comment]
awesome

**Comment by cammyjee** [comment]
@asoltys I know you're busy with baby stuff. Do you know which domain registrar dctrl.ca is setup with?

**Comment by asoltys** [comment]
Looks like easyDNS https://whois.cira.ca/public


   WHOIS search results
   Domain name:   dctrl.ca
   Domain name status:   registered
   Creation date:   2016/06/23
   Expiry date:   2017/06/23
   Updated date:   2016/12/11
   DNSSEC:   Unsigned

   Registrar name:   easyDNS Technologies Inc.
   Registrar number:   88

   Registrant name:   Blackcat Informatics Inc.

   *Administrative contact*
   Name:   Patrick Audley
   Postal address:   902 - 1325 Rolston St.
   Vancouver BC V6B0M2 Canada
   Phone:   +1.6048682856
   Fax:
   Email:   domains@blackcatinformatics.ca

   *Technical contact*
   Name:   Patrick Audley
   Postal address:   902 - 1325 Rolston St.
   Vancouver BC V6B0M2 Canada
   Phone:   +1.6048682856
   Fax:
   Email:   domains@blackcatinformatics.ca

   *Name servers*
   DNS 1 hostname:   ns1.digitalocean.com
   DNS 2 hostname: ns2.digitalocean.com
   DNS 3 hostname: ns3.digitalocean.com

**Comment by cammyjee** [comment]
@asoltys Got it, emails should be done shortly. Any chance you can get the site live soon? I'm assuming the digital ocean servers are running on our server? @paullucas @findkiko @TRhode I made a shared folder in last pass for DCTRL secrets if you want to add pi admins/server admin etc. in there. Or just send them to me and I'll put them in.

**Comment by cammyjee** [comment]
site is live
