### ISSUE TITLE
create @dctrl.ca emails

### ISSUE THREAD

**Issue by cammyjee** [DecentralVan/decentral#182]
I'm going to create some @dctrl.ca emails soon if you want one please post in here or msg me.

**Comment by astupidmoose** [comment]
Might be a good idea to have a general or multiple "placeholder" emails such as info@, membership@, payments@ or a catchall for these. Would be good with multiple people allowed to log into a general one and send on behalf of the whole group, for example membership renewals

**Comment by cammyjee** [comment]
@astupidmoose good call!

**Comment by mitchplze** [comment]
Does anyone have any objections if I take over this, and involve y'all in it? Just need the DNS/domain login info!

**Comment by cammyjee** [comment]
@brownmgb Hey Mitch, yes please! I've been banging my head trying to get the domain verified like I was telling you. I'll message you with login info.

**Comment by JayeHarrill** [comment]
Yes!! Progress!!

**Comment by mitchplze** [comment]
Email system is all setup and good to go. Meeting agenda item: addresses, creating them, best practices, etc.
