### ISSUE TITLE
Make Wiki searchable with Algolia

### ISSUE THREAD

**Issue by manv3lez** [DecentralVan/decentral#189]
There is a lot of detailed information about the meat space in the Decentral Wiki, thanks mainly to @chiselinc.

The wiki is ideal for maintaining the repo up to date, but currently there is no easy way for members, specially new ones, to access it, aside from going directly to it.

Integrating Algolia would allow members to find out details about the space.

**Comment by rheaplex** [comment]
GitHub search now supports better wiki searching - 
https://github.com/DctrlVan/DCTRL/search?type=Wikis&q=in%3Abody+projector
