### ISSUE TITLE
Sidewalk Hackathon

### ISSUE THREAD

**Issue by ghost** [DecentralVan/decentral#29]

**Comment by ghost** [comment]
Can we set a day for this, believe I could get some interest from Launch / Lighthouse and I bet the SFU guys we know would be interested. I am willing to put up some prize bitcoin up to make things interesting.

**Comment by findkiko** [comment]
Some inspiration: https://vimeo.com/118919656

**Comment by chiselinc** [comment]
@TRhode are you still into this or should we shelve it for now?

**Comment by findkiko** [comment]
It's still something we want to do. My opinion is that this is mainly blocked on the creation of some more formal scheduler/mgmt system for sending data or uploading code to the hardware. There's no authentication system at present.

**Comment by chiselinc** [comment]
This constantly happens now, no need for hackathon
