### ISSUE TITLE
We need more RFID tags for the EMlock

### ISSUE THREAD

**Issue by cammyjee** [DecentralVan/decentral#3]
I tried reading one with my phone to copy the ID on an RFID card but it didn't work. Should we just order more of the same ones?

**Comment by findkiko** [comment]
ACK. I believe the type specified was 'EM' rfid cards, but would need to double-check the instructions for that reader, it's on there somewhere.

Related note: Adding the new cards to the system currently requires access to the pin pad to punch in an admin code, so bear that in mind if you're re-re-enforcing the door. There's supposed to be a way of having a special add-a-card card. But I think the idea is to move the system over to a better rfid reader anyway.

Side note: The door system I started a seperate 'smartprop' repo for. More code-ish issues should live there where they can be addressed directly by committed code.

**Comment by findkiko** [comment]
These look like the same ones. http://www.ebay.ca/itm/LOT-20-EM-4100-4102-Keychains-125Khz-RFID-Proximity-ID-Card-Token-Tags-Key-Fobs-/291196285082

**Comment by cammyjee** [comment]
ordered!
