### ISSUE TITLE
Truck day

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#34]
- [x] Get chopsaw from Kiko's
- [x] Table hardware from homedepot
- [x] Sheet materials for shelves etc. from homedepot.
- [ ] Dumpster/Recycle run?
- [ ] Craigslist furniture pick-ups?

**Comment by astupidmoose** [comment]
I can probably help with this. My truck has a 5.5' bed, and I have straps to tie things down. If we can get everything arranged for Feb 5th, I can be around most of the day. If anything is needed sooner PM me on slack and we can talk. - Mike O.

**Comment by findkiko** [comment]
Sounds good. Thanks Mike.
