### ISSUE TITLE
mount push-to-exit properly

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#4]
@sterky

Any way we can use that back box that used to be a light switch?

Also, what's wrong with a light switch at the entrance? makes a lot of sense to me, esp. at the top of a dark staircase.

**Comment by sterky** [comment]
It still can be a light switch, but not a 3-way circuit so both upstairs and down need to be on for like

The box has constant 120V in it as well to clean up wiring with armors cable to a box housing everything

**Comment by findkiko** [comment]
I looked hard for a matching back-box in Home Depot but no luck, The switch has screw terminals in a 75mm square grid. I bought a standard rectangular PVC box+faceplate and hope to hack it in or possibly 3D print some kind of adapter to make it look nice.

The alternative is to just swap it out for a standard format momentary switch and add our own "push-to-exit" graphics etc.
