### ISSUE TITLE
Create Decentral Webstore / Shirts

### ISSUE THREAD

**Issue by cammyjee** [DecentralVan/decentral#41]
Take pictures of people wearing shirts

**Comment by cammyjee** [comment]
- [ ] T-Shirts

**Comment by astupidmoose** [comment]
I think OpenBazaar is perfect for this. Someone will need to be responsible for management and running the store though. We should also brainstorm a list of items that we can put up (Memberships?). 

I can help set this up on one of the machines in the space, or anyone who wants to play around with a setup can also do so.

Keirnan and I will be hosting the openbazaar night on May 20th, but I think it would be cool to have the shop up and running before then so we can use decentral as an example of a running store.

**Comment by BenMorganIO** [comment]
I can help set this up :)
