### ISSUE TITLE
Visitor book / Suggestion (troll) box

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#51]
Perhaps an old laptop running a full-screen app. The idea being that people can just approach and start typing or scroll through old messages.

The key features being speed and optional anonymity.

**Comment by cammyjee** [comment]
Got an old Toshiba laptop just needs 15v DC 5.0amps power adpater

**Comment by findkiko** [comment]
The power supply needs a round ~5mm jack. If anyone is at FreeGeek soon that might be the best bet for finding this.

**Comment by chiselinc** [comment]
Seems like this is a pretty dead project-- I think we need to get our house in order as far as polishing up the wiki, expectations, documentation etc-- otherwise we'd be getting a lot of input around things that have clear answers/solutions that just aren't publicly accessible at present
