### ISSUE TITLE
Bangtown table top

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#54]
We need a way to keep the rustic charm of the Bangtown table top but make it comfortable for daily use...

I was thinking about some coloured work mats that can be removed when not in use. Ikea has these round ones that are cheap and could look cool. Though a bigger rectangle would be more ideal for working on. Plus these are textured so not as good for writing/drawing on.

http://www.ikea.com/ca/en/catalog/products/30132457/#/30132457

**Comment by findkiko** [comment]
Also maybe it's just the lack of lighting but the Bangtown sign is a little dreary, I'd also be down if the artists want to paint something cool and colourful on one of the OSB 4x8s, then we can throw that over the top for daily use instead?

**Comment by astupidmoose** [comment]
What if we do a clear coat of polyurethane overtop? Or perhaps a sheet of plexiglass?

**Comment by findkiko** [comment]
Plexiglass is a good call, any idea what a thin 4x8 sheet of plexiglass would cost us?

**Comment by findkiko** [comment]
~$100 for plexiglass. No rush on this. Closing.
