### ISSUE TITLE
Makerfaire

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#55]
Confirm this years hardware (+ art?) projects and commit to a Makerfaire booth.

We need to also think about our branding strategy for this.

I'm thinking our main project should be the tele-presence robot, but open to ideas.

It might also be a good opportunity to publicize a more interactive/polished sidewalk demo, or maybe we could do an award ceremony for the sidewalk hackathon entries at makerfaire. (Actual demos work better at night).

**Comment by findkiko** [comment]
Would be great to locate my pull-down projector screen for this. It was very useful last year and I have no idea where it's gone to, last seen in the main room by the coats (Note: it's not the little blue one that's there now).

**Comment by astupidmoose** [comment]
I should be free makerfaire weekend to help out with the booth as needed, we can also use my truck for move-in/move-out if needed.

**Comment by findkiko** [comment]
March 15 is application deadline. $60 for groups/non-profit. Perhaps this might be better served under the bitcoin co-op umbrella?
