### ISSUE TITLE
Create official process and checklist for scheduling events.

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#59]
Document it in the wiki.

**Comment by findkiko** [comment]
Can somebody add a thumbs up or down to this issue. I'm curious how we can use it for voting...

**Comment by astupidmoose** [comment]
I was able to add both.. lol

**Comment by findkiko** [comment]
Cool. It does shows who did what. so we can filter out members from non-members etc.

**Comment by findkiko** [comment]
If you thumb-up twice it cancels out.. :confused:

**Comment by cammyjee** [comment]
We now have a wiki page for setting up events.
