### ISSUE TITLE
Door RFID reader

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#6]
The current RFID reader does not capture individual IDs, so cannot be used in a computerised system.
- [x] Determine the suitability of the arduino version that @sterky has.
- [ ] Test new reader
- [ ] Mount new reader.
- [ ] Screw door re-enforcement back on.

**Comment by Latrasis** [comment]
@cammyjee: Here's the rfid shield you asked for: https://www.adafruit.com/products/364

I remember finding it from this tutorial on setting up a reader with a pi, should be useful:
http://pikiosk.tumblr.com/post/51812205794/07-reading-rfid-tags-with-the-raspberry-pi

**Comment by cammyjee** [comment]
Thanks Jake, @sterky what do you think of above?

**Comment by findkiko** [comment]
Moved to wiki.

**Comment by cammyjee** [comment]
@TRhode @findkiko @Latrasis I was able to get the NFC reader to read via headless raspberry pi through platformio. I guess now we can write some code for it?
