### ISSUE TITLE
Enable or re-implement BitHub for our repos.

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#60]
Enable pay-per-commit donation system to encourage participation. See [bithub repo](https://github.com/WhisperSystems/BitHub) for details.

Note: The above implementation would require holding some funds at coinbase.

**Comment by BenMorganIO** [comment]
Coinbase has given up on integration with Canada. I'm currently working on my own ATM: https://github.com/receptr/bithub. Coinbase API keys take 48 hours to activate, which means if you do want to set it up, you have to start your work, wait 2 days, and then continue your work. The project also hasn't been touched in 2 years and even then, the docs were out of date. So, get ready to dive into (actually well written) java code.

Notably on the roadmap for this Bithub I've been working on:
- Ask for bitcoin address from user's Github email. This way the app comes to them for asking for money.
- Whitelist GH users with a Toggl application to pay per the time they spent working on a feature.
- Mark issues with bounties and payout upon completion.
- Integrate with Copay to have multisig authentication.
- Have Slackbot notify the admins about the work and wait for approval on their end to release the bitcoin to the user.

I've only just been working on it today and plan to spend some of my Sunday tomorrow working on it. Let me know if you're interested and I can help you beta test it as well.

**Comment by findkiko** [comment]
Hi, thanks for the input. The features all sound great. I'll keep an eye on it. I'd love to help implement it but currently busy with meatspace projects.
