### ISSUE TITLE
Make qr-codes for equipment and procedures

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#71]
Link them to the wiki for further explanations.

**Comment by astupidmoose** [comment]
I have a brother label printer and roll of 2.4 in labels i won't be using. I can dedicate some time in the next few weeks to making this happen if its still something that we want to be doing. 

2.4" Labels might be a bit big, but i'd have to buy any other sizes we wanted. Should be able to use any label size that fits into a brother label printer.

**Comment by findkiko** [comment]
I can't say this is top of my list, but...
The best starting point would just be a set of small integer bar-code stickers (25-50?). The rest can be done via myturn.com (what the Vancouver tool library uses) or similar.

**Comment by findkiko** [comment]
We can always cut the labels down, or print 2/4 per sticker.
