### ISSUE TITLE
Procure / make a larger coffee table

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#73]

**Comment by astupidmoose** [comment]
I've added an alert to my phone from the craigslist free section for a coffee table. Will post in the slack if anything decent pops up and looks like we might be able to get it. Any direction on what exactly we would would? Size/Color/Vibe?

**Comment by chiselinc** [comment]
are we pretty happy with the coffee tables we have now? i am constantly navigating the maze that is our main space with all the furniture and i can't see how we could fit anything more. close this issue perhaps?

**Comment by findkiko** [comment]
Much as I like closing issues. I left this open because I don't really like our coffee tables as an interior designer, (just so obviously $9 Ikea, lowest-common-denominator, soulless products). I liked the idea of building some replacements when I had free time. Close it if you feel strongly about shortening the issue list.
