### ISSUE TITLE
Put felt pads on dining chairs

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#76]
The feet make a horrible sound during meetings and recordings etc.

**Comment by astupidmoose** [comment]
I have felt pads from a Costco pack. If I remember I'll try to bring them next time I'm around

**Comment by findkiko** [comment]
Bump, (if you're coming to the meeting) :smile:

**Comment by astupidmoose** [comment]
Just put them into my backpack, remind me to give them to you before the meeting :)

**Comment by findkiko** [comment]
These didn't work very well due to the metal pins. Oh well.
