### ISSUE TITLE
Streamline and prioritize wishlist

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#79]
From the last meeting:
- Batteries, coils & temperature guage to test boyv (build your own vaporizer)
- Materials for Sofa plinth/storage boxes etc.
- Another projector. 
- Mic stand
- Radio mic
- New monitor
- Dedicated server box
- More raspberry pies
- Guitar 
- Keyboard
- Sandwich maker
- Magazine subscriptions
- Newspapers
- Keg, kegorator parts
- Paint for hall, main room, backroom, add some colour?
- Better router.
- Code school, lynda or similar
- Castors
- First aid kit
- Random hardware, screws
- Roomba
- Misc electronics/sensors for IOT & automation at decentral
- Mag lock for back door
- Raspberry Pi's / Beagle Bone Black
- Another Hot Plate
- Long Ethernet cables

**Comment by chiselinc** [comment]
Remove roomba, put a regular vacuum cleaner. I'm happy to vacuum if we get one, it will be way more efficient and long lasting.

**Comment by chiselinc** [comment]
Also why newspaper/magazines?

Dude you're going to be REALLY unhappy that I'm actually using this now, I'm going to have a million annoying questions

**Comment by chiselinc** [comment]
@findkiko maybe we can make a page on the wiki divided into two sections: shopping list [for necessities] and requested donations?

i'm willing to put that together tomorrowish if you think this is a good strategy. if not let me know how you'd suggest we proceed

**Comment by findkiko** [comment]
Maybe just stick with issues, that way there's a comment thread for each class of wishlist. to be clear; I'm saying this issue can be broken into multiple sub-issues eg. "costco list" and say "shared equipment proposals"

**Comment by chiselinc** [comment]
sounds good, i'm going to comment for each with "task list" format a little later-- working on a project rn.

**Comment by chiselinc** [comment]
I got a number of bins/organizing thingies, a first aid kit, a good butcher and paring knife, some extra cutlery, thus far for space organization. The rest of what I'll be getting in terms of organization/cleaning stuff:
- [ ] Microwave splatter cover
- [ ] Oven mitts for microwave [I think I have some]
- [x] Cutting board
- [x] Sink plug [to soak dishes/clean sink]
- [ ] Comet cleaner [they didn't have it at costco]
- [ ] Baking soda [to deodorize fridge]
- [x] Antiseptic [the first aid kit, mindbogglingly, did not have it]

Gotta look around when I get a chance, to determine what else.

**Comment by chiselinc** [comment]
**Wishlist [Donations/**not*\* priority for budget! -- anything we want to genuinely pursue should be run by a quorum of members]**
- [ ]     Batteries, coils & temperature guage to test boyv (build your own vaporizer)
- [ ]     Materials for Sofa plinth/storage boxes etc.
- [ ]     Another projector. 
- [ ]  More raspberry pis
- [ ]     Guitar 
- [x]     Keyboard
- [ ]     Sandwich maker
- [ ]     Code school, lynda or similar
- [ ]  Misc electronics/sensors for IOT & automation at decentral

**Comment by chiselinc** [comment]
**Space Stuff to Get [keep an eye out for good deals]**
- [ ]     Random hardware, screws
- [ ]     Vacuum
- [ ]     Lockitron for back room door
- [ ]     New monitor
- [x]     Dedicated server box
- [ ]     Keg, kegorator parts
- [ ]     Better router.
- [ ]     Castors
- [x]     Mic stand
- [ ]     Radio mic

**Comment by cammyjee** [comment]
Bought Mic Stand, printer cartridge, stock pot, first aid kit, and rat traps.

**Comment by findkiko** [comment]
- [ ] Network switch (passive)

@cammyjee Did we order the 2nd mag-lock or not?

**Comment by cammyjee** [comment]
@findkiko I have it in a wishlist on ebay. Taylors credit card wont work for some reason, so we'll need someone else to buy the items.

I'll ask around

**Comment by findkiko** [comment]
I'm closing this as its a mess now. (It'll still be visible as a closed issue). We can re-create a more up to date list somewhere.
