### ISSUE TITLE
costco trip

### ISSUE THREAD

**Issue by chiselinc** [DecentralVan/decentral#85]
tons of toilet paper
paper towels
[huge] trash bags

**Comment by cammyjee** [comment]
@chiselinc @findkiko Do we need anything else? I'm going with Jared on Friday afternoon. @adymitruk could you get the car for then? Otherwise I can use an evo

**Comment by chiselinc** [comment]
LIST FOR TOMORROW
- [x] As much toilet paper as possible
- [x] Same for paper towels
- [x] Dish washing sponges
- [x] Two huge hand soap refill things
- [x] Multipurpose spray cleaner bottle refill
- [ ] Comet/abrasive cleaner
- [x] I think they have huge bags of sugar packets?
- [x] Tons of trash bags

For the "tons of" items, seriously, tons of. As much as possible.

@findkiko add anything you can think of before tomorrow, they're going then

**Comment by findkiko** [comment]
I'm think we still need a better hand-towel situation. I have expectations that the "towel drive" won't be forthcoming, take a look at a pack of cheap towels at costco. Ikea ones were almost _too_ nice.
