### ISSUE TITLE
look into matrix.org as a possibility to migrate from slack, report back

### ISSUE THREAD

**Issue by chiselinc** [DecentralVan/decentral#93]

**Comment by chiselinc** [comment]
@astupidmoose you've expressed interest in this, i've got a lot on my plate, would you be down to follow up and report back your thoughts at the next meeting?

**Comment by astupidmoose** [comment]
Sure I can do this, however I would like to install this on the server that we acquire for the space so this might be delayed until then. Unless we have a space run digital ocean account that I can install this into a VPS?

**Comment by findkiko** [comment]
As an over-arching migration strategy. I think we should move all our mgmt stuff over to a new private system like matrix, leave existing slack as a general chit-chat, reddit-like forum for discussing the news etc. When people become official members, they then get access to our private system.

**Comment by chiselinc** [comment]
I think that's a great idea @findkiko .... as far as the server I finally heard back from Jacob Steeves, his friend's comp is a no go, I think Patrick checked out Free Geek so we can find that out from him.
