### ISSUE TITLE
server computer project

### ISSUE THREAD

**Issue by chiselinc** [DecentralVan/decentral#94]
Jacob Steeves said he'd czech out that $50 option-- follow up with him [and make him sign up on github for chrissake]

@paudley and me will scope free geek if that doesn't work

**Comment by astupidmoose** [comment]
Have a friend who is getting rid of an older gaming rig/tower. Said he wanted about $350 for it but it should have some decent CPU/GPU processing power. I will post the specs for discussion once i have them to see if its an option

**Comment by paudley** [comment]
Thanks!   @chiselinc, @paullucas @Latrasis, when is a good time to check out the prices at Free Geek?

**Comment by chiselinc** [comment]
Hmmm later this week would work for me @paudley, haven't heard from Jacob Steeves about his friends comp, he said he'd stop by today or tomorrow so I'll try to catch him.

**Comment by astupidmoose** [comment]
http://vancouver.craigslist.ca/bnc/sys/5631453962.html

This is my buddy's rig. If there is interest for it, I can ask how much he would take for it but I think he was set on about $350 which would be higher than the budget we set however I can always pursue if we are interested and see if he would come down at all. 

It has 6 hard drive slots on the case and 3 optical slots.

**Comment by paudley** [comment]
Let's take a trip to FreeGeek before the end of the week if we can and get a sense of their prices as well.   That system is probably a good deal but I think we want a little more ram and the ssd is a little small so we'll have to grab some additional parts.

Is anyone free for a run to FreeGeek tomorrow or Thursday around lunch-ish?
(note: paudley does not drive so if you are coming it's a walk/bus)

**Comment by chiselinc** [comment]
i completely missed this followup @paudley, jake said you mentioned free geek the other day so we can chat about what options you potentially found-- since you evaluated the options in person w/ your tech expertise, if we come to a conclusion i can pick the hardware up, i live a ten min walk from there

**Comment by chiselinc** [comment]
Jacob Steeves private messaged me on Slack, he followed up with his friend and that computer is a no go, just as a heads up.

**Comment by findkiko** [comment]
I think we're happy for now
