### ISSUE TITLE
finish cashing out tangerine account

### ISSUE THREAD

**Issue by chiselinc** [DecentralVan/decentral#95]
Full Crypto 4 Lyfe

**Comment by chiselinc** [comment]
@findkiko can you "cash it out" into my pocket plz, to whatever degree we're willing to switch to full crypto right now, and i can send bitcoin?

we also need a budget for the costco trip/some cleaning and organizing stuff. i suppose the larger discussion can happen at the members meeting but i'm hoping to ask the members for a discretionary $60 or so on slack to get some stuff to better clean/organize the space this week-- we'd greatly benefit from some dollar store bins etc in the cupboards to hold the stuff that's been stored in opaque plastic bags up until this point :)

**Comment by chiselinc** [comment]
@cammyjee this got handled, right?

**Comment by chiselinc** [comment]
@cammyjee did this ever get completed?

**Comment by cammyjee** [comment]
@chiselinc sorry, missed that last one. I called them to close it but they wouldn't let me unless I transferred the funds into my personal account, which I can't do for liability reasons. The $ has slowly been sucked out to auto-pay the internet bill and other things. $163 left, should be empty soon if @findkiko wants to cash it out or use to buy a few more things.
