### ISSUE TITLE
beta test new cleaning arrangement

### ISSUE THREAD

**Issue by chiselinc** [DecentralVan/decentral#96]
1 week, monitoring how much actual time it takes to keep the space clean

**Comment by findkiko** [comment]
Do we think something like this would stand a chance in the space? https://www.homedepot.ca/en/home/p.floormate-deluxe-hard-floor-cleaner.1000848459.html

**Comment by astupidmoose** [comment]
Might be a decent investment. Do we have a lockable storage locker so this type stuff doesn't walk away? 

> https://www.homedepot.ca/en/home/p.floormate-deluxe-hard-floor-cleaner.1000848459.html

Cheaper on Amazon.ca if we do get it, plus we could try to use purse.io and get the 15-20% off and pay with btc.

**Comment by chiselinc** [comment]
We definitely need a storage locker, esp since the removal of the red ones is still looming. As a cheap ass yankee i would def argue for getting it cheaper, and as far as model it's not like we're cleaning the ritz Carlton haha

**Comment by findkiko** [comment]
re: timing experiment. I Just spent an hour washing up, recycling, vacuuming hallway.

**Comment by chiselinc** [comment]
yeah it looks great kiko! re:beta testing the general cleaning, that's been difficult since we didn't have any goddamn cleaning supplies. i brought spray cleaner and we still have a bit of comet for the toilet. last week it took about 2 hours total but like i said i couldn't clean the sink, "kitchen area", mirrors etc. without stuff. i'll report back in after cleaning tomorrow morning.

**Comment by chiselinc** [comment]
yeah this stuff is hella work-- one of the reasons i think we need a public facing one pager is it's ridiculous how many people leave trash around the space after meetups. every single day that i come in i'm throwing coffee cups etc away. i'm sure i'm not the only one encountering this.

anywho i'll ping the channel later on my request for a short term supplies budget-- @findkiko i'll be there this evening so if you're feeling better we could talk space organization and where i should go from here, otherwise i'll just keep cleaning stuff up and set aside the things that i need your input on

**Comment by findkiko** [comment]
My take on this is that meet-ups need an "owner", the owner must be an active member, active member is responsible for cleaning up after their guests. Too many recurring meetups where the host isn't present or clearly identified so there isn't really any structure or agenda.

**Comment by paudley** [comment]
I'm strongly in favor of having an active member responsible for each meetup.  That means that someone is there to control access and keep an eye on the space.

**Comment by chiselinc** [comment]
Agreed, we've had issues with this though, so we'll have to Make It Be Known in a more formal way.
