### ISSUE TITLE
Find a home for home-brew equipment.

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#97]

**Comment by chiselinc** [comment]
wondering about the viability of that room on the other side of the workshop, with the door directly across from the sink? it's pretty empty, we could move stuff to the side, and it would keep things out of view so they don't get messed with

**Comment by findkiko** [comment]
I'm thinking we need to organize a trip to the dump for a load of the junk in the back room, then use that space for more day-to-day storage.

**Comment by chiselinc** [comment]
Done today with Tanna and Cam.
