### ISSUE TITLE
Build draining board adjacent to sink.

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#98]
We really need a drying rack within arms reach from the industrial sink.

**Comment by chiselinc** [comment]
Omg my thoughts exactly. Was discussing this with kiko, i think people would actually do dishes if they knew where to put them. I got a "sponge holder" to hang on the sink so the sponge air dries properly and they last longer.

**Comment by chiselinc** [comment]
Also to mount a compost near there for coffee grounds.

**Comment by chiselinc** [comment]
Cam and I figured out a useful fix, it should work for the foreseeable future [folding minitable with existing drainer on top]
